from tkinter import *
root=Tk()
root.geometry("1366x768")
Label(root,text="  ").grid(row=0,column=0,padx=100)
label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
pic=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\Bus_for_Project.png')
Label(root,image=pic).grid(row=0,column=1,columnspan=12)
label1.grid(row=1,column=1,pady=15,columnspan=12)
Label(root,text="ADD BUS OPERATOR DETAIL",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=12)
Label(root,text="Operator Id",font=("Aerial 15")).grid(row=4,column=1)
Entry(root,width=5).grid(row=4,column=2)
Label(root,text="Name",font=("Aerial 15")).grid(row=4,column=3)
Entry(root,width=7).grid(row=4,column=4)
Label(root,text="Address",font=("Aerial 15")).grid(row=4,column=5)
Entry(root).grid(row=4,column=6)
Label(root,text="Phone",font=("Aerial 15")).grid(row=4,column=7)
Entry(root).grid(row=4,column=8)
Label(root,text="Email",font=("Aerial 15")).grid(row=4,column=9)
Entry(root).grid(row=4,column=10)
Button(root,text="Add",bg="green",font=("Aerial 12")).grid(row=4,column=11)
Button(root,text="Edit",bg="green",font=("Aerial 12")).grid(row=4,column=12,padx=5)
root.mainloop()
