from tkinter import *
root=Tk()
root.geometry("1366x768")
Label(root,text="  ").grid(row=0,column=0,padx=200)
label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
pic=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\Bus_for_Project.png')
Label(root,image=pic).grid(row=0,column=1,columnspan=4)
label1.grid(row=1,column=1,pady=15,columnspan=4)
Label(root,text="Add New Details To Database",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=4)
Button(root,text="New Operator",font=("Aerial 15 bold"),bg="green").grid(row=3,column=1,padx=30)
Button(root,text="New Bus",font=("Aerial 15 bold"),bg="orange").grid(row=3,column=2)
Button(root,text="New Route",font=("Aerial 15 bold"),bg="sky blue").grid(row=3,column=3,padx=30)
Button(root,text="New Run",font=("Aerial 15 bold"),bg="purple").grid(row=3,column=4)
root.mainloop()
