from tkinter import *
root=Tk()
root.geometry("1366x768")
Label(root,text="  ").grid(row=0,column=0,padx=150)
label1=Label(root,text="Online Bus Booking System",font=("Aerial 30 bold"),fg="red",bg="sky blue")
pic=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\Bus_for_Project.png')
Label(root,image=pic).grid(row=0,column=1,columnspan=12)
label1.grid(row=1,column=1,pady=15,columnspan=12)
Label(root,text="Add Bus Route Detail",font=("Aerial 20 bold"),fg="green",bg="white").grid(row=2,column=1,pady=15,columnspan=12)
Label(root,text="Route id",font=("Aerial 15")).grid(row=4,column=1)
Entry(root,width=5).grid(row=4,column=2)
Label(root,text="Station Name",font=("Aerial 15")).grid(row=4,column=3)
Entry(root,width=15).grid(row=4,column=4)
Label(root,text="Station Id",font=("Aerial 15")).grid(row=4,column=5)
Entry(root).grid(row=4,column=6)
Button(root,text="Add Route",bg="green",font=("Aerial 13")).grid(row=4,column=11)
Button(root,text="Delete Route",bg="green",font=("Aerial 13")).grid(row=4,column=12,padx=5)
pic1=PhotoImage(file='C:\\Users\\DEBANJAN SINGHA ROY\\OneDrive\\Desktop\\Bus Reservation System\\home.png')
Button(root,image=pic1).grid(row=10,column=8,padx=10,pady=50)
root.mainloop()
